#!/usr/bin/env python
#
# File        : wscript
# Description : Waf build script.
# Copyright   : Copyright (c) 2016 Mirror Labs Inc. All rights reserved.
# Maintainer  : Enzo Haussecker <enzo@mirror.co>
# Stability   : Stable
# Portability : Portable
#
# NOTICE: Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# This script compiles, minifies and installs all JavaScript source files.
##

import os

top = ".."
out = "%s/build" % top

sources = ["app.jsx"]

def configure(ctx):
    # Find Babel compiler.
    ctx.find_program("babel", var = "BABEL")
    # Find YUI compressor.
    ctx.find_program("yui-compressor", var = "YUI")
    # Find JSX Transformer.
    ctx.find_file("babel-plugin-transform-react-jsx", "/usr/local/lib/node_modules")
    # Set environment variables.
    ctx.env.PLUGINS = "--plugins /usr/local/lib/node_modules/babel-plugin-transform-react-jsx"

def build(ctx):
    for source in sources:
        name, _ = os.path.splitext(source)
        # Compile source file.
        ctx(rule   = "${BABEL} ${PLUGINS} ${SRC} -o ${TGT}",
            source = source,
            target = "%s-compiled.js" % name)
        # Minify source file.
        ctx(rule   = "${YUI} ${SRC} -o ${TGT}",
            source = "%s-compiled.js" % name,
            target = "%s.min.js" % name)
        # Install source.
        ctx.install_files("/tmp/assets/js", "%s.min.js" % name)

def test(ctx):
    pass
